FROM php:7.4-fpm-alpine
WORKDIR /app

RUN apk --update upgrade \
    && apk add --no-cache autoconf automake make gcc g++ icu-dev rabbitmq-c rabbitmq-c-dev \
    && pecl install amqp-1.9.4 \
    && pecl install apcu-5.1.17 \
    && pecl install xdebug-2.9.4 \
    && docker-php-ext-install -j$(nproc) \
        bcmath \
        opcache \
        intl \
        pdo_mysql \
    && docker-php-ext-enable \
        amqp \
        apcu \
        opcache

COPY etc/infrastructure/php/ /usr/local/etc/php/

RUN chmod 777 /var/log

RUN apk add --no-cache supervisor

COPY /etc/infrastructure/supervisord/supervisord.conf /etc/supervisord.conf


CMD ["supervisord","-c","/etc/supervisord.conf"]

