accounts_put:
  path: /accounts/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Accounts\AccountsPutController
  defaults: { auth: false}
  methods:  [PUT]

accounts_get:
  path: /accounts/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Accounts\AccountsGetController
  defaults: { auth: false}
  methods:  [GET]

accounts_list:
  path: /accounts
  controller: Myfinance\Apps\Portal\Backend\Controller\Accounts\AccountsGetAllController
  defaults: { auth: false, roles: ROLE_USER}
  methods:  [GET]


