categories_put:
  path: /categories/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Categories\CategoriesPutController
  defaults: { auth: false}
  methods:  [PUT]

categories_get:
  path: /categories/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Categories\CategoriesGetController
  defaults: { auth: true, roles: ROLE_USER}
  methods:  [GET]

categories_list:
  path: /categories
  controller: Myfinance\Apps\Portal\Backend\Controller\Categories\CategoriesGetAllController
  defaults: { auth: true, roles: ROLE_USER}
  methods:  [GET]
