groups_put:
  path: /groups/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Groups\GroupsPutController
  defaults: { auth: true, roles: ROLE_USER}
  methods:  [PUT]

groups_get:
  path: /groups/{id}
  controller: Myfinance\Apps\Portal\Backend\Controller\Groups\GroupsGetController
  defaults: { auth: true, roles: ROLE_USER}
  methods:  [GET]

groups_list:
  path: /groups
  controller: Myfinance\Apps\Portal\Backend\Controller\Groups\GroupsGetAllController
  defaults: { auth: true, roles: ROLE_USER}
  methods:  [GET]


