framework:
  test: true


services:
  _defaults:
    autoconfigure: true
    autowire: true

  Myfinance\Tests\:
    resource: '../../../../tests/src'

  # Tagging

  Myfinance\Tests\Shared\Infrastructure\Symfony\InsertUserTokenMiddleware:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300}


  # Instance selector
  Myfinance\Portal\Categories\Domain\CategoryRepository: '@Myfinance\Portal\Categories\Infrastructure\Persistence\DoctrineCategoryRepository'