services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [Myfinance\Portal\Shared\Infrastructure\Doctrine\PortalEntityManagerFactory, create]
    arguments:
      - driver:   '%env(PORTAL_DATABASE_DRIVER)%'
        host:     '%env(PORTAL_DATABASE_HOST)%'
        port:     '%env(PORTAL_DATABASE_PORT)%'
        dbname:   '%env(PORTAL_DATABASE_NAME)%'
        user:     '%env(PORTAL_DATABASE_USER)%'
        password: '%env(PORTAL_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: myfinance.database_connection }
    public: true


  # Courses
  #Myfinance\Api\Courses\Domain\CourseRepository: '@Myfinance\Api\Courses\Infrastructure\Persistence\DoctrineCourseRepository'

