monolog:
  handlers:
    # this "file_log" key could be anything
    file_log:
      type: stream
      path: "%kernel.project_dir%/var/log/%kernel.environment%.log"
      # log *all* messages (debug is lowest level)
      level: debug

    syslog_handler:
      type: syslog
      # log error-level messages and higher
      level: error